/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="next/navigation-types/compat/navigation" />

// NOTE: This file should not be edited directly. It is automatically generated by Next.js and
// includes type definitions for the Next.js runtime. See https://nextjs.org/ for details.